# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WatchaPedia < Formula
  desc "왓챠 피디아 CLI (guinness API 래핑)"
  homepage "https://github.com/michael-lim-watcha/homebrew-tap"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/michael-lim-watcha/homebrew-tap/releases/download/v0.1.0/watcha-pedia_darwin_amd64.tar.gz"
      sha256 "d06badd3ebd5e62a9e96c350bd0876b4aa1bafd57631cdc109b38f42d2bae4ea"

      define_method(:install) do
        bin.install "watcha-pedia"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/michael-lim-watcha/homebrew-tap/releases/download/v0.1.0/watcha-pedia_darwin_arm64.tar.gz"
      sha256 "d509e57e697bff5061513ac4f412e43e6c467d08f202cf787c798d316e956692"

      define_method(:install) do
        bin.install "watcha-pedia"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/michael-lim-watcha/homebrew-tap/releases/download/v0.1.0/watcha-pedia_linux_amd64.tar.gz"
      sha256 "3e54462997ad0d6a5b18d8e696eb5d5ad367c58fc97e28dbbca8af31ca5daadd"
      define_method(:install) do
        bin.install "watcha-pedia"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/michael-lim-watcha/homebrew-tap/releases/download/v0.1.0/watcha-pedia_linux_arm64.tar.gz"
      sha256 "c7ded2f34a4d139e729a1376a95310d654168ed2807ee9d016f03d59e48f149b"
      define_method(:install) do
        bin.install "watcha-pedia"
      end
    end
  end

  test do
    system "#{bin}/watcha-pedia", "--help"
  end
end
