# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WatchaPedia < Formula
  desc "왓챠 피디아 CLI (guinness API 래핑)"
  homepage "https://github.com/michael-lim-watcha/homebrew-tap"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/michael-lim-watcha/homebrew-tap/releases/download/v0.2.0/watcha-pedia_darwin_amd64.tar.gz"
      sha256 "de73d0fd6cb64704e5f74d0aca034c082de2483d094b71a671dbb9e1240366b0"

      define_method(:install) do
        bin.install "watcha-pedia"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/michael-lim-watcha/homebrew-tap/releases/download/v0.2.0/watcha-pedia_darwin_arm64.tar.gz"
      sha256 "9415b506ba7abdffe7b36cccd2184be25e4bdc548b1d9d2ac63988b78b9a5cb5"

      define_method(:install) do
        bin.install "watcha-pedia"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/michael-lim-watcha/homebrew-tap/releases/download/v0.2.0/watcha-pedia_linux_amd64.tar.gz"
      sha256 "68892a621f99821dcb70c2502c2e5db2aa0836bede6a301882329a88253f880e"
      define_method(:install) do
        bin.install "watcha-pedia"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/michael-lim-watcha/homebrew-tap/releases/download/v0.2.0/watcha-pedia_linux_arm64.tar.gz"
      sha256 "d0f667d4130aad055b9598b3baac8b07ff5a3f76634673c9cbfc967adfd0357a"
      define_method(:install) do
        bin.install "watcha-pedia"
      end
    end
  end

  test do
    system "#{bin}/watcha-pedia", "--help"
  end
end
