# This file was generated by GoReleaser. DO NOT EDIT.
cask "khao" do
  name "khao"
  desc "사내 IDP CLI"
  homepage "https://github.com/michael-lim-watcha/homebrew-tap"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "khao"

  on_macos do
    on_intel do
      url "https://github.com/michael-lim-watcha/homebrew-tap/releases/download/v#{version}/khao_darwin_amd64.tar.gz"
      sha256 "24eed01024a2ecdcd6f45676789da775712bedc1b011b9531ed0924003724b4b"
    end
    on_arm do
      url "https://github.com/michael-lim-watcha/homebrew-tap/releases/download/v#{version}/khao_darwin_arm64.tar.gz"
      sha256 "c08d237a45ea980fd66b807e8ac8c76c8ebf67951fbc836f08cce3f7afec7d17"
    end
  end

  # No zap stanza required
end
