# This file was generated by GoReleaser. DO NOT EDIT.
cask "khao" do
  name "khao"
  desc "IDP(platform.kubecha.com) CLI (khao API 래핑)"
  homepage "https://github.com/michael-lim-watcha/homebrew-tap"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "khao"

  on_macos do
    on_intel do
      url "https://github.com/michael-lim-watcha/homebrew-tap/releases/download/v#{version}/khao_darwin_amd64.tar.gz"
      sha256 "9eb7e0b2e6ee8a6b7d6c922ccf284440b702593694f95d0f0964394eb43179c1"
    end
    on_arm do
      url "https://github.com/michael-lim-watcha/homebrew-tap/releases/download/v#{version}/khao_darwin_arm64.tar.gz"
      sha256 "65310b104e605975cf3ec3481f126d4d40b91c9c47817214bb885d8ebdbb45f5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/michael-lim-watcha/homebrew-tap/releases/download/v#{version}/khao_linux_amd64.tar.gz"
      sha256 "74e6317a1e0e4cd5bac9d298608fac4ae8d2a45db4cd3d2a47797f56d0ab11f8"
    end
    on_arm do
      url "https://github.com/michael-lim-watcha/homebrew-tap/releases/download/v#{version}/khao_linux_arm64.tar.gz"
      sha256 "7f87630e205761e21fcea8957f1e81b7309caa269a8fa9d1ca0b9403a3bde413"
    end
  end

  # No zap stanza required
end
