# This file was generated by GoReleaser. DO NOT EDIT.
cask "watcha-pedia" do
  name "watcha-pedia"
  desc "왓챠 피디아 CLI (guinness API 래핑)"
  homepage "https://github.com/michael-lim-watcha/homebrew-tap"
  version "0.3.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "watcha-pedia"

  on_macos do
    on_intel do
      url "https://github.com/michael-lim-watcha/homebrew-tap/releases/download/v#{version}/watcha-pedia_darwin_amd64.tar.gz"
      sha256 "46c92adf10e025dcb0f26f8f6e536b8b9fe14ad0f1f0726ca6127f5c2ec62746"
    end
    on_arm do
      url "https://github.com/michael-lim-watcha/homebrew-tap/releases/download/v#{version}/watcha-pedia_darwin_arm64.tar.gz"
      sha256 "0960186e586cef7859402aa32f30b53c568beb71f5eca1f097bc54db6dd610c4"
    end
  end

  # No zap stanza required
end
