# This file was generated by GoReleaser. DO NOT EDIT.
cask "watcha-pedia" do
  name "watcha-pedia"
  desc "왓챠 피디아 CLI (guinness API 래핑)"
  homepage "https://github.com/michael-lim-watcha/homebrew-tap"
  version "0.3.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "watcha-pedia"

  on_macos do
    on_intel do
      url "https://github.com/michael-lim-watcha/homebrew-tap/releases/download/v#{version}/watcha-pedia_darwin_amd64.tar.gz"
      sha256 "f0a3c0bad228c969bb0a27c9f099021ce954f3707b39c929ec05f820432d76ee"
    end
    on_arm do
      url "https://github.com/michael-lim-watcha/homebrew-tap/releases/download/v#{version}/watcha-pedia_darwin_arm64.tar.gz"
      sha256 "65d9c38df3c16535fffe3a0a723f0fe319e2eac41fa047dc2b7caad92479e4c3"
    end
  end

  # No zap stanza required
end
